import { Inter } from "next/font/google";
import { Footer } from "../components/Footer";
import { BG } from "../components/mainBG";
import { Navigation } from "../components/navBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TVS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <div className="flex flex-col w-screen">
            <BG />
            <Navigation />
            <div className="flex-grow">{children}</div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}