import { Inter } from "next/font/google";
import { BG } from "../components/mainBG";
import { Navigation } from "../components/navBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TVS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BG/>
        <Navigation />
          {children}
        <BG/>
      </body>
    </html>
  );
}
